import type { Brand, Category, Product } from "@/types";

export const headerData = [
  {
    title: "Home",
    href: "/",
  },
  {
    title: "Shop",
    href: "/shop",
  },
  {
    title: "Categories",
    href: "/categories",
  },
  {
    title: "About",
    href: "/about",
  },
  {
    title: "Contact",
    href: "/contact",
  },
];

export const categoriesData: Category[] = [
  {
    id: "cat-medicines",
    title: "Medicines",
    slug: "medicines",
    description: "Over-the-counter and prescription medicines",
    image: "/images/categories/placeholder.svg",
  },
  {
    id: "cat-vitamins",
    title: "Vitamins & Supplements",
    slug: "vitamins-supplements",
    description: "Daily vitamins, minerals and nutritional supplements",
    image: "/images/categories/placeholder.svg",
  },
  {
    id: "cat-personal-care",
    title: "Personal Care",
    slug: "personal-care",
    description: "Everyday personal hygiene and grooming essentials",
    image: "/images/categories/placeholder.svg",
  },
  {
    id: "cat-skin-care",
    title: "Skin Care",
    slug: "skin-care",
    description: "Cleansers, moisturisers and sun protection",
    image: "/images/categories/placeholder.svg",
  },
  {
    id: "cat-baby-care",
    title: "Baby Care",
    slug: "baby-care",
    description: "Gentle care products for babies and infants",
    image: "/images/categories/placeholder.svg",
  },
  {
    id: "cat-mother-care",
    title: "Mother Care",
    slug: "mother-care",
    description: "Care essentials for mothers and mothers-to-be",
    image: "/images/categories/placeholder.svg",
  },
  {
    id: "cat-devices",
    title: "Medical Devices",
    slug: "medical-devices",
    description: "Monitors, thermometers and home medical equipment",
    image: "/images/categories/placeholder.svg",
  },
  {
    id: "cat-first-aid",
    title: "First Aid",
    slug: "first-aid",
    description: "Bandages, antiseptics and first-aid supplies",
    image: "/images/categories/placeholder.svg",
  },
  {
    id: "cat-wellness",
    title: "Health & Wellness",
    slug: "health-wellness",
    description: "General health, fitness and wellness products",
    image: "/images/categories/placeholder.svg",
  },
  {
    id: "cat-oral-care",
    title: "Oral Care",
    slug: "oral-care",
    description: "Toothpastes, brushes and mouth care products",
    image: "/images/categories/placeholder.svg",
  },
];

/**
 * SAMPLE CATALOG DATA
 *
 * These products are placeholder/seed data so the store can be developed and
 * tested. Manufacturer names are fictional samples. Replace with the real
 * Pharmaco inventory (this data will also be used to seed the database).
 */

export const brandsData: Brand[] = [
  {
    id: "brand-sample-pharma",
    title: "Sample Pharma",
    slug: "sample-pharma",
    description: "Sample pharmaceutical brand for medicines",
    image: "/images/brands/placeholder.svg",
  },
  {
    id: "brand-wellco",
    title: "Wellco Laboratories",
    slug: "wellco-laboratories",
    description: "Sample brand for everyday medicines and wellness",
    image: "/images/brands/placeholder.svg",
  },
  {
    id: "brand-nutrisample",
    title: "NutriSample",
    slug: "nutrisample",
    description: "Sample vitamins and supplements brand",
    image: "/images/brands/placeholder.svg",
  },
  {
    id: "brand-caresample",
    title: "CareSample",
    slug: "caresample",
    description: "Sample personal care and first-aid brand",
    image: "/images/brands/placeholder.svg",
  },
  {
    id: "brand-dermasample",
    title: "DermaSample",
    slug: "dermasample",
    description: "Sample skin care brand",
    image: "/images/brands/placeholder.svg",
  },
  {
    id: "brand-babysample",
    title: "BabySample",
    slug: "babysample",
    description: "Sample baby and mother care brand",
    image: "/images/brands/placeholder.svg",
  },
  {
    id: "brand-medisample",
    title: "MediSample Devices",
    slug: "medisample-devices",
    description: "Sample medical devices brand",
    image: "/images/brands/placeholder.svg",
  },
];

export const productsData: Product[] = [
  {
    id: "prod-001",
    name: "Paracetamol 500mg Tablets (20s)",
    slug: "paracetamol-500mg-tablets",
    description:
      "Paracetamol 500mg tablets for the relief of mild pain and fever. Pack of 20 tablets. Always read the label and use as directed.",
    categorySlug: "medicines",
    price: 120,
    discount: 0,
    stock: 150,
    sku: "MED-001",
    images: ["/images/products/placeholder.svg"],
    requiresPrescription: false,
    isFeatured: true,
    rating: 4.7,
    reviewCount: 132,
    genericName: "Paracetamol",
    strength: "500mg",
    dosageForm: "Tablet",
    brandSlug: "sample-pharma",
    manufacturer: "Sample Pharma Ltd",
    createdAt: "2026-07-01T10:00:00.000Z",
  },
  {
    id: "prod-002",
    name: "Ibuprofen 400mg Tablets (10s)",
    slug: "ibuprofen-400mg-tablets",
    description:
      "Ibuprofen 400mg tablets for the relief of pain and inflammation. Pack of 10 tablets. Use as directed by a pharmacist or doctor.",
    categorySlug: "medicines",
    price: 180,
    discount: 10,
    stock: 90,
    sku: "MED-002",
    images: ["/images/products/placeholder.svg"],
    requiresPrescription: false,
    isFeatured: false,
    rating: 4.5,
    reviewCount: 58,
    genericName: "Ibuprofen",
    strength: "400mg",
    dosageForm: "Tablet",
    brandSlug: "sample-pharma",
    manufacturer: "Sample Pharma Ltd",
    createdAt: "2026-06-20T10:00:00.000Z",
  },
  {
    id: "prod-003",
    name: "Amoxicillin 500mg Capsules (12s)",
    slug: "amoxicillin-500mg-capsules",
    description:
      "Amoxicillin 500mg capsules. Antibiotic available only with a valid prescription. Dispensed under pharmacist supervision.",
    categorySlug: "medicines",
    price: 350,
    discount: 0,
    stock: 40,
    sku: "MED-003",
    images: ["/images/products/placeholder.svg"],
    requiresPrescription: true,
    isFeatured: false,
    rating: 4.8,
    reviewCount: 21,
    genericName: "Amoxicillin",
    strength: "500mg",
    dosageForm: "Capsule",
    brandSlug: "sample-pharma",
    manufacturer: "Sample Pharma Ltd",
    createdAt: "2026-06-15T10:00:00.000Z",
  },
  {
    id: "prod-004",
    name: "Cetirizine 10mg Tablets (10s)",
    slug: "cetirizine-10mg-tablets",
    description:
      "Cetirizine 10mg antihistamine tablets for the relief of allergy symptoms. Pack of 10 tablets.",
    categorySlug: "medicines",
    price: 95,
    discount: 5,
    stock: 200,
    sku: "MED-004",
    images: ["/images/products/placeholder.svg"],
    requiresPrescription: false,
    isFeatured: false,
    rating: 4.6,
    reviewCount: 74,
    genericName: "Cetirizine",
    strength: "10mg",
    dosageForm: "Tablet",
    brandSlug: "wellco-laboratories",
    manufacturer: "Wellco Laboratories",
    createdAt: "2026-07-18T10:00:00.000Z",
  },
  {
    id: "prod-005",
    name: "Omeprazole 20mg Capsules (14s)",
    slug: "omeprazole-20mg-capsules",
    description:
      "Omeprazole 20mg capsules for the relief of heartburn and acid reflux. Pack of 14 capsules.",
    categorySlug: "medicines",
    price: 260,
    discount: 0,
    stock: 0,
    sku: "MED-005",
    images: ["/images/products/placeholder.svg"],
    requiresPrescription: false,
    isFeatured: false,
    rating: 4.4,
    reviewCount: 39,
    genericName: "Omeprazole",
    strength: "20mg",
    dosageForm: "Capsule",
    brandSlug: "wellco-laboratories",
    manufacturer: "Wellco Laboratories",
    createdAt: "2026-05-30T10:00:00.000Z",
  },
  {
    id: "prod-006",
    name: "Insulin Glargine 100IU/ml Pen",
    slug: "insulin-glargine-pen",
    description:
      "Long-acting insulin glargine pre-filled pen. Available only with a valid prescription. Requires cold-chain storage.",
    categorySlug: "medicines",
    price: 2450,
    discount: 0,
    stock: 15,
    sku: "MED-006",
    images: ["/images/products/placeholder.svg"],
    requiresPrescription: true,
    isFeatured: false,
    rating: 4.9,
    reviewCount: 12,
    genericName: "Insulin Glargine",
    strength: "100IU/ml",
    dosageForm: "Injection (pre-filled pen)",
    brandSlug: "sample-pharma",
    manufacturer: "Sample Pharma Ltd",
    createdAt: "2026-07-25T10:00:00.000Z",
  },
  {
    id: "prod-007",
    name: "Vitamin C 1000mg Effervescent Tablets (20s)",
    slug: "vitamin-c-1000mg-effervescent",
    description:
      "Vitamin C 1000mg effervescent tablets with orange flavour. Supports daily vitamin C intake. Pack of 20 tablets.",
    categorySlug: "vitamins-supplements",
    price: 450,
    discount: 15,
    stock: 120,
    sku: "VIT-001",
    images: ["/images/products/placeholder.svg"],
    requiresPrescription: false,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 210,
    genericName: "Ascorbic Acid",
    strength: "1000mg",
    dosageForm: "Effervescent tablet",
    brandSlug: "nutrisample",
    manufacturer: "NutriSample Co",
    createdAt: "2026-07-22T10:00:00.000Z",
  },
  {
    id: "prod-008",
    name: "Multivitamin Daily Tablets (30s)",
    slug: "multivitamin-daily-tablets",
    description:
      "Daily multivitamin and mineral tablets. One-a-day formula, pack of 30 tablets.",
    categorySlug: "vitamins-supplements",
    price: 680,
    discount: 0,
    stock: 85,
    sku: "VIT-002",
    images: ["/images/products/placeholder.svg"],
    requiresPrescription: false,
    isFeatured: true,
    rating: 4.6,
    reviewCount: 95,
    dosageForm: "Tablet",
    brandSlug: "nutrisample",
    manufacturer: "NutriSample Co",
    createdAt: "2026-07-10T10:00:00.000Z",
  },
  {
    id: "prod-009",
    name: "Vitamin D3 2000IU Softgels (60s)",
    slug: "vitamin-d3-2000iu-softgels",
    description:
      "Vitamin D3 2000IU softgel capsules supporting daily vitamin D intake. Pack of 60 softgels.",
    categorySlug: "vitamins-supplements",
    price: 850,
    discount: 10,
    stock: 60,
    sku: "VIT-003",
    images: ["/images/products/placeholder.svg"],
    requiresPrescription: false,
    isFeatured: false,
    rating: 4.7,
    reviewCount: 67,
    genericName: "Cholecalciferol",
    strength: "2000IU",
    dosageForm: "Softgel",
    brandSlug: "nutrisample",
    manufacturer: "NutriSample Co",
    createdAt: "2026-06-28T10:00:00.000Z",
  },
  {
    id: "prod-010",
    name: "Omega-3 Fish Oil 1000mg Capsules (60s)",
    slug: "omega-3-fish-oil-1000mg",
    description:
      "Omega-3 fish oil 1000mg capsules providing EPA and DHA. Pack of 60 capsules.",
    categorySlug: "vitamins-supplements",
    price: 1150,
    discount: 0,
    stock: 45,
    sku: "VIT-004",
    images: ["/images/products/placeholder.svg"],
    requiresPrescription: false,
    isFeatured: false,
    rating: 4.5,
    reviewCount: 41,
    strength: "1000mg",
    dosageForm: "Capsule",
    brandSlug: "nutrisample",
    manufacturer: "NutriSample Co",
    createdAt: "2026-05-12T10:00:00.000Z",
  },
  {
    id: "prod-011",
    name: "Gentle Antibacterial Hand Wash 250ml",
    slug: "antibacterial-hand-wash-250ml",
    description:
      "Gentle antibacterial hand wash with moisturising ingredients. 250ml pump bottle.",
    categorySlug: "personal-care",
    price: 320,
    discount: 0,
    stock: 140,
    sku: "PC-001",
    images: ["/images/products/placeholder.svg"],
    requiresPrescription: false,
    isFeatured: false,
    rating: 4.4,
    reviewCount: 52,
    brandSlug: "caresample",
    manufacturer: "CareSample Ltd",
    createdAt: "2026-07-05T10:00:00.000Z",
  },
  {
    id: "prod-012",
    name: "Anti-Dandruff Shampoo 200ml",
    slug: "anti-dandruff-shampoo-200ml",
    description:
      "Anti-dandruff shampoo for daily use. Helps reduce visible flakes. 200ml bottle.",
    categorySlug: "personal-care",
    price: 550,
    discount: 20,
    stock: 75,
    sku: "PC-002",
    images: ["/images/products/placeholder.svg"],
    requiresPrescription: false,
    isFeatured: true,
    rating: 4.3,
    reviewCount: 88,
    brandSlug: "caresample",
    manufacturer: "CareSample Ltd",
    createdAt: "2026-07-15T10:00:00.000Z",
  },
  {
    id: "prod-013",
    name: "Roll-On Deodorant Fresh 50ml",
    slug: "roll-on-deodorant-fresh-50ml",
    description: "Long-lasting roll-on deodorant with a fresh scent. 50ml.",
    categorySlug: "personal-care",
    price: 280,
    discount: 0,
    stock: 110,
    sku: "PC-003",
    images: ["/images/products/placeholder.svg"],
    requiresPrescription: false,
    isFeatured: false,
    rating: 4.2,
    reviewCount: 34,
    brandSlug: "caresample",
    manufacturer: "CareSample Ltd",
    createdAt: "2026-06-08T10:00:00.000Z",
  },
  {
    id: "prod-014",
    name: "Hydrating Face Moisturiser 100ml",
    slug: "hydrating-face-moisturiser-100ml",
    description:
      "Lightweight hydrating face moisturiser suitable for normal to dry skin. 100ml tube.",
    categorySlug: "skin-care",
    price: 750,
    discount: 10,
    stock: 65,
    sku: "SK-001",
    images: ["/images/products/placeholder.svg"],
    requiresPrescription: false,
    isFeatured: true,
    rating: 4.6,
    reviewCount: 119,
    brandSlug: "dermasample",
    manufacturer: "DermaSample Inc",
    createdAt: "2026-07-20T10:00:00.000Z",
  },
  {
    id: "prod-015",
    name: "Sunscreen SPF 50+ 100ml",
    slug: "sunscreen-spf-50-100ml",
    description:
      "Broad-spectrum SPF 50+ sunscreen lotion. Water resistant. 100ml tube.",
    categorySlug: "skin-care",
    price: 980,
    discount: 0,
    stock: 55,
    sku: "SK-002",
    images: ["/images/products/placeholder.svg"],
    requiresPrescription: false,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 156,
    brandSlug: "dermasample",
    manufacturer: "DermaSample Inc",
    createdAt: "2026-07-24T10:00:00.000Z",
  },
  {
    id: "prod-016",
    name: "Gentle Foaming Face Wash 150ml",
    slug: "gentle-foaming-face-wash-150ml",
    description:
      "Gentle foaming face wash for daily cleansing. Suitable for sensitive skin. 150ml.",
    categorySlug: "skin-care",
    price: 620,
    discount: 5,
    stock: 0,
    sku: "SK-003",
    images: ["/images/products/placeholder.svg"],
    requiresPrescription: false,
    isFeatured: false,
    rating: 4.4,
    reviewCount: 47,
    brandSlug: "dermasample",
    manufacturer: "DermaSample Inc",
    createdAt: "2026-06-01T10:00:00.000Z",
  },
  {
    id: "prod-017",
    name: "Baby Diapers Size 3 (52s)",
    slug: "baby-diapers-size-3",
    description:
      "Soft, breathable baby diapers with leak protection. Size 3 (6–10kg), pack of 52.",
    categorySlug: "baby-care",
    price: 1450,
    discount: 8,
    stock: 70,
    sku: "BB-001",
    images: ["/images/products/placeholder.svg"],
    requiresPrescription: false,
    isFeatured: true,
    rating: 4.7,
    reviewCount: 203,
    brandSlug: "babysample",
    manufacturer: "BabySample Co",
    createdAt: "2026-07-12T10:00:00.000Z",
  },
  {
    id: "prod-018",
    name: "Baby Gentle Lotion 200ml",
    slug: "baby-gentle-lotion-200ml",
    description:
      "Mild, hypoallergenic baby lotion for delicate skin. Dermatologically tested. 200ml.",
    categorySlug: "baby-care",
    price: 480,
    discount: 0,
    stock: 95,
    sku: "BB-002",
    images: ["/images/products/placeholder.svg"],
    requiresPrescription: false,
    isFeatured: false,
    rating: 4.5,
    reviewCount: 61,
    brandSlug: "babysample",
    manufacturer: "BabySample Co",
    createdAt: "2026-06-18T10:00:00.000Z",
  },
  {
    id: "prod-019",
    name: "Baby Wipes Fragrance-Free (72s)",
    slug: "baby-wipes-fragrance-free",
    description:
      "Fragrance-free baby wipes enriched with aloe vera. Pack of 72 wipes.",
    categorySlug: "baby-care",
    price: 350,
    discount: 0,
    stock: 180,
    sku: "BB-003",
    images: ["/images/products/placeholder.svg"],
    requiresPrescription: false,
    isFeatured: false,
    rating: 4.6,
    reviewCount: 84,
    brandSlug: "babysample",
    manufacturer: "BabySample Co",
    createdAt: "2026-07-08T10:00:00.000Z",
  },
  {
    id: "prod-020",
    name: "Prenatal Multivitamin Tablets (30s)",
    slug: "prenatal-multivitamin-tablets",
    description:
      "Prenatal multivitamin tablets with folic acid and iron. Pack of 30 tablets. Use as advised by your healthcare provider.",
    categorySlug: "mother-care",
    price: 890,
    discount: 10,
    stock: 50,
    sku: "MC-001",
    images: ["/images/products/placeholder.svg"],
    requiresPrescription: false,
    isFeatured: false,
    rating: 4.7,
    reviewCount: 73,
    dosageForm: "Tablet",
    brandSlug: "nutrisample",
    manufacturer: "NutriSample Co",
    createdAt: "2026-07-02T10:00:00.000Z",
  },
  {
    id: "prod-021",
    name: "Nursing Pads Disposable (30s)",
    slug: "nursing-pads-disposable",
    description:
      "Soft, absorbent disposable nursing pads with adhesive strips. Pack of 30.",
    categorySlug: "mother-care",
    price: 520,
    discount: 0,
    stock: 40,
    sku: "MC-002",
    images: ["/images/products/placeholder.svg"],
    requiresPrescription: false,
    isFeatured: false,
    rating: 4.4,
    reviewCount: 29,
    brandSlug: "babysample",
    manufacturer: "BabySample Co",
    createdAt: "2026-06-25T10:00:00.000Z",
  },
  {
    id: "prod-022",
    name: "Digital Blood Pressure Monitor",
    slug: "digital-blood-pressure-monitor",
    description:
      "Automatic upper-arm digital blood pressure monitor with memory function and large display.",
    categorySlug: "medical-devices",
    price: 5200,
    discount: 12,
    stock: 25,
    sku: "DEV-001",
    images: ["/images/products/placeholder.svg"],
    requiresPrescription: false,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 91,
    brandSlug: "medisample-devices",
    manufacturer: "MediSample Devices",
    createdAt: "2026-07-19T10:00:00.000Z",
  },
  {
    id: "prod-023",
    name: "Digital Thermometer",
    slug: "digital-thermometer",
    description:
      "Fast-reading digital thermometer with flexible tip and fever alert. Suitable for all ages.",
    categorySlug: "medical-devices",
    price: 650,
    discount: 0,
    stock: 100,
    sku: "DEV-002",
    images: ["/images/products/placeholder.svg"],
    requiresPrescription: false,
    isFeatured: false,
    rating: 4.5,
    reviewCount: 118,
    brandSlug: "medisample-devices",
    manufacturer: "MediSample Devices",
    createdAt: "2026-06-10T10:00:00.000Z",
  },
  {
    id: "prod-024",
    name: "Blood Glucose Monitor Kit",
    slug: "blood-glucose-monitor-kit",
    description:
      "Blood glucose monitoring kit including meter, lancing device and 10 test strips.",
    categorySlug: "medical-devices",
    price: 3800,
    discount: 0,
    stock: 18,
    sku: "DEV-003",
    images: ["/images/products/placeholder.svg"],
    requiresPrescription: false,
    isFeatured: false,
    rating: 4.6,
    reviewCount: 44,
    brandSlug: "medisample-devices",
    manufacturer: "MediSample Devices",
    createdAt: "2026-05-22T10:00:00.000Z",
  },
  {
    id: "prod-025",
    name: "Pulse Oximeter Fingertip",
    slug: "pulse-oximeter-fingertip",
    description:
      "Fingertip pulse oximeter measuring blood oxygen saturation (SpO2) and pulse rate.",
    categorySlug: "medical-devices",
    price: 1850,
    discount: 15,
    stock: 35,
    sku: "DEV-004",
    images: ["/images/products/placeholder.svg"],
    requiresPrescription: false,
    isFeatured: false,
    rating: 4.4,
    reviewCount: 66,
    brandSlug: "medisample-devices",
    manufacturer: "MediSample Devices",
    createdAt: "2026-07-14T10:00:00.000Z",
  },
  {
    id: "prod-026",
    name: "Adhesive Bandages Assorted (40s)",
    slug: "adhesive-bandages-assorted",
    description:
      "Sterile adhesive bandages in assorted sizes. Breathable and water resistant. Pack of 40.",
    categorySlug: "first-aid",
    price: 220,
    discount: 0,
    stock: 160,
    sku: "FA-001",
    images: ["/images/products/placeholder.svg"],
    requiresPrescription: false,
    isFeatured: false,
    rating: 4.5,
    reviewCount: 57,
    brandSlug: "caresample",
    manufacturer: "CareSample Ltd",
    createdAt: "2026-06-30T10:00:00.000Z",
  },
  {
    id: "prod-027",
    name: "Antiseptic Solution 100ml",
    slug: "antiseptic-solution-100ml",
    description:
      "Antiseptic solution for cleaning minor cuts, wounds and grazes. 100ml bottle.",
    categorySlug: "first-aid",
    price: 190,
    discount: 0,
    stock: 130,
    sku: "FA-002",
    images: ["/images/products/placeholder.svg"],
    requiresPrescription: false,
    isFeatured: false,
    rating: 4.6,
    reviewCount: 72,
    brandSlug: "sample-pharma",
    manufacturer: "Sample Pharma Ltd",
    createdAt: "2026-07-06T10:00:00.000Z",
  },
  {
    id: "prod-028",
    name: "First Aid Kit Home (42 pieces)",
    slug: "first-aid-kit-home",
    description:
      "Compact home first-aid kit with 42 essentials including bandages, gauze, tape and scissors.",
    categorySlug: "first-aid",
    price: 1250,
    discount: 10,
    stock: 30,
    sku: "FA-003",
    images: ["/images/products/placeholder.svg"],
    requiresPrescription: false,
    isFeatured: true,
    rating: 4.7,
    reviewCount: 38,
    brandSlug: "caresample",
    manufacturer: "CareSample Ltd",
    createdAt: "2026-07-21T10:00:00.000Z",
  },
  {
    id: "prod-029",
    name: "ORS Electrolyte Sachets (10s)",
    slug: "ors-electrolyte-sachets",
    description:
      "Oral rehydration salt sachets for restoring fluids and electrolytes. Pack of 10 sachets.",
    categorySlug: "health-wellness",
    price: 250,
    discount: 0,
    stock: 145,
    sku: "HW-001",
    images: ["/images/products/placeholder.svg"],
    requiresPrescription: false,
    isFeatured: false,
    rating: 4.6,
    reviewCount: 49,
    dosageForm: "Powder sachet",
    brandSlug: "wellco-laboratories",
    manufacturer: "Wellco Laboratories",
    createdAt: "2026-07-03T10:00:00.000Z",
  },
  {
    id: "prod-030",
    name: "Hot Water Bottle 2L",
    slug: "hot-water-bottle-2l",
    description:
      "Classic 2-litre hot water bottle with soft knitted cover for warmth and comfort.",
    categorySlug: "health-wellness",
    price: 780,
    discount: 0,
    stock: 42,
    sku: "HW-002",
    images: ["/images/products/placeholder.svg"],
    requiresPrescription: false,
    isFeatured: false,
    rating: 4.3,
    reviewCount: 26,
    brandSlug: "caresample",
    manufacturer: "CareSample Ltd",
    createdAt: "2026-05-28T10:00:00.000Z",
  },
  {
    id: "prod-031",
    name: "Knee Support Brace Medium",
    slug: "knee-support-brace-medium",
    description:
      "Elastic knee support brace providing compression and support. Size medium.",
    categorySlug: "health-wellness",
    price: 950,
    discount: 5,
    stock: 28,
    sku: "HW-003",
    images: ["/images/products/placeholder.svg"],
    requiresPrescription: false,
    isFeatured: false,
    rating: 4.4,
    reviewCount: 31,
    brandSlug: "medisample-devices",
    manufacturer: "MediSample Devices",
    createdAt: "2026-06-14T10:00:00.000Z",
  },
  {
    id: "prod-032",
    name: "Fluoride Toothpaste 120g",
    slug: "fluoride-toothpaste-120g",
    description:
      "Fluoride toothpaste for daily cavity protection and fresh breath. 120g tube.",
    categorySlug: "oral-care",
    price: 260,
    discount: 0,
    stock: 190,
    sku: "OC-001",
    images: ["/images/products/placeholder.svg"],
    requiresPrescription: false,
    isFeatured: false,
    rating: 4.5,
    reviewCount: 102,
    brandSlug: "caresample",
    manufacturer: "CareSample Ltd",
    createdAt: "2026-07-09T10:00:00.000Z",
  },
  {
    id: "prod-033",
    name: "Antibacterial Mouthwash 250ml",
    slug: "antibacterial-mouthwash-250ml",
    description:
      "Alcohol-free antibacterial mouthwash for daily oral hygiene. 250ml bottle.",
    categorySlug: "oral-care",
    price: 430,
    discount: 10,
    stock: 88,
    sku: "OC-002",
    images: ["/images/products/placeholder.svg"],
    requiresPrescription: false,
    isFeatured: false,
    rating: 4.4,
    reviewCount: 63,
    brandSlug: "caresample",
    manufacturer: "CareSample Ltd",
    createdAt: "2026-07-16T10:00:00.000Z",
  },
  {
    id: "prod-034",
    name: "Soft Bristle Toothbrush (Pack of 2)",
    slug: "soft-bristle-toothbrush-2pack",
    description:
      "Soft bristle toothbrushes designed for gentle, effective cleaning. Pack of 2.",
    categorySlug: "oral-care",
    price: 180,
    discount: 0,
    stock: 210,
    sku: "OC-003",
    images: ["/images/products/placeholder.svg"],
    requiresPrescription: false,
    isFeatured: false,
    rating: 4.3,
    reviewCount: 45,
    brandSlug: "caresample",
    manufacturer: "CareSample Ltd",
    createdAt: "2026-06-22T10:00:00.000Z",
  },
];
